### PR TITLE
Fix #2

### LINKED ISSUE #2: Failed to activate the status-bar package
[Enter steps to reproduce below:]
1. Open Atom

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.4.1
### Stack Trace

Failed to activate the status-bar package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
  at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
  at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
  at ProfilesTile.initialize (/Users/particle/Projects/Atom/particle-dev-profiles/src/profiles-tile.js:44:23)
  at ProfilesTile.View [as constructor] (/Users/particle/Projects/Atom/particle-dev-profiles/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new ProfilesTile (/Users/particle/Projects/Atom/particle-dev-profiles/src/profiles-tile.js:27:76)
  at Object.consumeStatusBar (/Users/particle/Projects/Atom/particle-dev-profiles/src/main.js:33:10)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
  at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:355:71)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:779:28

```
### Commands

```
     -0:00.3.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui.white-cursor)
     -0:00.3.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui.white-cursor)
     -0:00.3.0 particle-dev:update-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui.white-cursor)
     -0:00.3.0 particle-dev:append-menu (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-one-dark-ui.white-cursor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "particle-offline-compiler",
      "platformio-ide",
      "platformio-ide-terminal",
      "particle-dev-local-compiler",
      "remote-edit"
    ],
    "excludeVcsIgnoredPaths": false,
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.38 (inactive)
autocomplete-clang, v0.10.0 (inactive)
build, vundefined (inactive)
clang-format, v1.25.0 (inactive)
console-panel, v0.2.0 (inactive)
docblockr, v0.8.7 (inactive)
elementary-light-ui, v0.26.2 (inactive)
emmet, v2.4.3 (inactive)
es6-javascript, v1.0.0 (inactive)
file-type-icons, v1.3.2 (inactive)
flex-tool-bar, v0.11.0 (inactive)
focus-dark, v1.1.0 (inactive)
hex, v0.6.2 (inactive)
imdone-atom, v1.3.31 (inactive)
indentation-indicator, v1.0.0 (inactive)
language-bats, v0.1.0 (inactive)
language-docker, v1.1.7 (inactive)
language-ini, v1.16.0 (inactive)
language-javascript-better, v1.7.1 (inactive)
language-particle, v0.3.4 (inactive)
language-svg, v0.9.0 (inactive)
line-count, v0.5.0 (inactive)
lines, v0.13.1 (inactive)
linter, v1.11.18 (inactive)
linter-cpplint, v1.0.1 (inactive)
linter-eslint, v8.0.0 (inactive)
linter-gcc, v0.6.15 (inactive)
monokai, v0.18.0 (inactive)
particle-dev, v0.1.5 (inactive)
particle-dev-cloud-functions, v0.1.0 (inactive)
particle-dev-cloud-variables, v0.1.0 (inactive)
particle-dev-libraries, v0.1.0 (inactive)
particle-dev-local-compiler, v0.0.4 (inactive)
particle-dev-profiles, v0.1.6 (inactive)
particle-offline-compiler, v0.0.0 (inactive)
platformio-ide, v1.6.0 (inactive)
platformio-ide-terminal, v2.2.0 (inactive)
pretty-json, v1.6.1 (inactive)
raml, v0.2.0 (inactive)
regex-railroad-diagram, v0.16.0 (inactive)
remote-edit, v1.8.24 (inactive)
search-all-keybindings, v0.1.6 (inactive)
svg-preview, v0.10.0 (inactive)
tabs-to-spaces, v1.0.2 (inactive)
tool-bar, v1.0.1 (inactive)
tool-bar-main, v0.0.10 (inactive)
unity-ui, v2.1.5 (inactive)
white-cursor, v0.6.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by suda**

### CODE REVIEW

File: src/profiles-tile.js [hunk 1]
```diff
@@ -20,24 +19,24 @@ export default class ProfilesTile extends View {
 
 		this.subscriptions = new CompositeDisposable();
 
-		this.subscriptions.add(this.targetPlatform.on('click', () => {
+		// On click handler
+		this.targetPlatform.on('click', () => {
```
Comment (stefan-moraru) [inline src/profiles-tile.js:23]: Is the removal of `this.subscription.add(fn)` going to affect any functionality?

Comment (suda) [reply src/profiles-tile.js:23]: No as using it previously was unnecessary. `CompositeDisposable` was disposing only `Disposable` instances and `.on()` and `_onCurrentTargetPlatformChanged()` don't return it anyway :)

**Review by stefan-moraru — APPROVED** [review]

**Review by stefan-moraru — APPROVED** [review]
Looks good! Great job!
